package com.boot.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Shipwreck")
public class Shipwreck {
	String id;
	String name;
	String description;
	String condition;
	Integer depth;
	Double latitude;
	Double longitude;
	Integer yeardiscovered;

	public Shipwreck() {
	}

	public Shipwreck(String id, String name, String description, String condition, Integer depth, Double latitude,
			Double longitude, Integer yeardiscovered) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.condition = condition;
		this.depth = depth;
		this.latitude = latitude;
		this.longitude = longitude;
		this.yeardiscovered = yeardiscovered;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBRangeKey(attributeName = "Name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "Description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@DynamoDBAttribute(attributeName = "Condition")
	public String getCondition() {
		return condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	@DynamoDBAttribute(attributeName = "Depth")
	public Integer getDepth() {
		return depth;
	}

	public void setDepth(Integer depth) {
		this.depth = depth;
	}

	@DynamoDBAttribute(attributeName = "Latitude")
	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@DynamoDBAttribute(attributeName = "Longitude")
	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@DynamoDBAttribute(attributeName = "YearDiscovered")
	public Integer getYearDiscovered() {
		return yeardiscovered;
	}

	public void setYearDiscovered(Integer yeardiscovered) {
		this.yeardiscovered = yeardiscovered;
	}

	@Override
	public String toString() {
		return "Shipwreck [id=" + id + ", name=" + name + ", description=" + description + ", condition=" + condition
				+ ", depth=" + depth + ", latitude=" + latitude + ", longitude=" + longitude + ", yeardiscovered="
				+ yeardiscovered + "]";
	}
	
	
}
